### ISSUE TITLE
wildfly::deployment behaving incorrectly on refresh event

### ISSUE THREAD

**Issue by LightAxe** [biemond/biemond-wildfly#142] opened 2016-08-31 15:39 UTC
I'm finding wildfly::deployment is undeploying the app, but not redeploying it, upon a refresh event:

```
  # Deploy applications (WAR files) if defined
  if (is_hash($applications)) {
    $applications.each |$name, $app| {
      archive { "/tmp/${name}":
        ensure       => present,
        extract      => false,
        extract_path => '/tmp',
        source       => $app[source],
        digest_url   => "${app[source]}.md5",
        digest_type  => 'md5',
      } ~>
      wildfly::deployment { $name:
        source  => "/tmp/${name}",
      }
    }
  }
```

Results in:

```
Info: Wildfly::Deployment[bc.war]: Scheduling refresh of Exec[download deployable from /tmp/bc.war]
Notice: /Stage[main]/Profile::Gwjboss/Wildfly::Deployment[bc.war]/Exec[download deployable from /tmp/bc.war]: Triggered 'refresh' from 1 events
Debug: /Stage[main]/Profile::Gwjboss/Wildfly::Deployment[bc.war]/Exec[download deployable from /tmp/bc.war]: The container Wildfly::Deployment[bc.war] will propagate my refresh event
Notice: /Stage[main]/Profile::Gwjboss/Wildfly::Deployment[bc.war]/File[/tmp/bc.war]/owner: owner changed 'root' to 'wildfly'
Notice: /Stage[main]/Profile::Gwjboss/Wildfly::Deployment[bc.war]/File[/tmp/bc.war]/group: group changed 'root' to 'wildfly'
Notice: /Stage[main]/Profile::Gwjboss/Wildfly::Deployment[bc.war]/File[/tmp/bc.war]/mode: mode changed '0644' to '0755'
Debug: /Stage[main]/Profile::Gwjboss/Wildfly::Deployment[bc.war]/File[/tmp/bc.war]: The container Wildfly::Deployment[bc.war] will propagate my refresh event
Debug: /Stage[main]/Profile::Gwjboss/Wildfly::Deployment[bc.war]/File[/tmp/bc.war]: The container Wildfly::Deployment[bc.war] will propagate my refresh event
Debug: /Stage[main]/Profile::Gwjboss/Wildfly::Deployment[bc.war]/File[/tmp/bc.war]: The container Wildfly::Deployment[bc.war] will propagate my refresh event
Debug: Wildfly_deployment[bc.war](provider=http_api): Exists? bc.war
Debug: Wildfly_deployment[bc.war](provider=http_api): Current content SHA1: 654294639d911683ebb29cf82abac67e3e7d9779
Debug: /Stage[main]/Profile::Gwjboss/Wildfly::Deployment[bc.war]/Wildfly_deployment[bc.war]/content: Should SHA1: 1dca5d8f8f3c198af490c98ac7e503b2d30d14a6 IS SHA1: 654294639d911683ebb29cf82abac67e3e7d9779
Debug: Wildfly_deployment[bc.war](provider=http_api): Updating deploy bc.war with content from file:/tmp/bc.war
Notice: /Stage[main]/Profile::Gwjboss/Wildfly::Deployment[bc.war]/Wildfly_deployment[bc.war]/content: content changed '654294639d911683ebb29cf82abac67e3e7d9779' to ''
Debug: /Stage[main]/Profile::Gwjboss/Wildfly::Deployment[bc.war]/Wildfly_deployment[bc.war]: The container Wildfly::Deployment[bc.war] will propagate my refresh event
Debug: Wildfly::Deployment[bc.war]: The container Class[Profile::Gwjboss] will propagate my refresh event
```

and in my console.log:

```
08:36:00,440 INFO  [org.jboss.web] (ServerService Thread Pool -- 56) JBAS018224: Unregister web context: /bc
......
08:36:02,144 INFO  [org.jboss.as.server.deployment] (MSC service thread 1-3) JBAS015877: Stopped deployment bc.war (runtime-name: bc.war) in 1715ms
08:36:02,220 INFO  [org.jboss.as.repository] (HttpManagementService-threads - 3) JBAS014901: Content removed from location /opt/jboss/standalone/data/content/65/4294639d911683ebb29cf82abac67e3e7d9779/content
08:36:02,221 INFO  [org.jboss.as.server] (HttpManagementService-threads - 3) JBAS018558: Undeployed "bc.war" (runtime-name: "bc.war")
```

Note the old bc.war is undeployed, but the new one is not deployed.

**Comment by LightAxe** [comment] 2016-09-01 16:23
More information:

I went packet diving, watching the traffic to the management port. Puppet is sending a request to undeploy, remove, add, and deploy, and JBoss is reporting all four operations as successful.  JBoss doesn't say what was successful, so I can't validate the order was correct, though.  I'm wondering if I'm running into an old JBoss bug.

**Comment by LightAxe** [comment] 2016-09-01 16:52
I rewrote update_deploy:

```
      def update_deploy(name, source, server_group)
        undeploy(name, server_group)
        deploy(name, source, server_group)
      end
```

and it's working for me now.  However, I suspect this isn't a change that you'll want to implement, as it breaks up a single action into two transactions.

Thoughts?

**Comment by jairojunior** [comment] 2016-10-30 16:04
Which JBoss/Wildfly version are you using?

**Comment by jairojunior** [comment] 2016-11-14 13:25
I believe it's a problem with remove and add the same resource inside a composite operation. Could you confirm your JBoss/Wildfly version?

The problem with breaking this into two operations is that if your new deploy fails, your previous deploy will be removed.

**Comment by LightAxe** [comment] 2016-11-14 16:05
It was happening with JBoss EAP 6.1.1; we've since moved to JBoss EAP 6.4.5 and I haven't tested the composite operation with 6.4.5.

We're actually working on moving deployments out of Puppet and into TFS, so I'm not sure how much effort is worth putting into this issue from my perspective if you think it's an oddball case due to a gargantuan application.

**Comment by jairojunior** [comment] 2016-11-14 16:23
Thanks. 

Just confirmed it's working with EAP 6.3 and 6.4 here, not sure how it maps to Wildfly releases, but won't fix this. No manpower to handle external bugs. 

Whether is this the best approach or not, it's hard to tell, some people are using some sort of Job Scheduler (RunDeck, UrbanCode), while others are using they CI servers (Jenkins, GitLab-CI, TFS) like you. 

Even saw some people using Ansible or Fabric with OS packages to package everything needed for deploy. Not to mention Docker. :smile:

**Closed by jairojunior** 2016-11-14 16:23 UTC

**Comment by mbosecke** [comment] 2017-07-19 23:10
I'm getting the same error. I'm using Wildfly 10.1.0 in a domain/slave configuration and biemond-wildfly v2.1.0. 

The deployment configuration for the master:
```
wildfly::deployment { 'app.war':
  source => "puppet:///files/app-jars/${environment}/app.war",
  server_group => 'app-group'
}
```

And after changing the war file on the puppet server, I see these logs on the wildfly master:
```
Jul 19 16:29:02 wildfly01 puppet-agent[18045]: (/Stage[main]/App/Wildfly::Deployment[app.war]/File[/opt/app.war]/content) content changed '{md5}a2d28aad44201188031aaeb25f3b9050' to '{md5}733b344c874c2c1c6475c4dad49e4d85'
Jul 19 16:29:07 wildfly01 puppet-agent[18045]: (/Stage[main]/App/Wildfly::Deployment[app.war]/Wildfly_deployment[app.war]/content) content changed '6585e7631a99e3bd963f99ed3f56da6b5dc52c56' to 'e0c4078355c2b75b90526415947435b373bb1e4c'
```

And then the slave instance will undeploy the application but makes no attempt in redeploying it after:
```
2017-07-19 16:29:06,852 INFO  [org.jboss.as.server.deployment] (MSC service thread 1-3) WFLYSRV0028: Stopped deployment app.war (runtime-name: app.war) in 307ms
2017-07-19 16:29:06,915 INFO  [org.jboss.as.server] (ServerService Thread Pool -- 85) WFLYSRV0009: Undeployed "app.war" (runtime-name: "app.war")
2017-07-19 16:29:06,932 INFO  [org.jboss.as.repository] (ServerService Thread Pool -- 85) WFLYDR0002: Content removed from location /opt/wildfly/domain/servers/app0
1-el/data/content/65/85e7631a99e3bd963f99ed3f56da6b5dc52c56/content
```

**Comment by piozygmunt** [comment] 2018-06-02 15:07
@mbosecke Having same problem, did you find any solutions ?

**Comment by mbosecke** [comment] 2018-06-02 15:14
I did not unfortunately :(

On Jun 2, 2018 9:07 AM, "piozygmunt" <notifications@github.com> wrote:

@mbosecke <https://github.com/mbosecke> Having same problem, did you find
any solutions ?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/biemond/biemond-wildfly/issues/142#issuecomment-394093924>,
or mute the thread

**Comment by piozygmunt** [comment] 2018-06-02 16:22
@mbosecke Dunno if you still need it but, as for now i came up with something like this: 
` wildfly::deployment { 'matcher.war':
      source            => $application_path
    }
    ->
    #quick fix 
    wildfly::cli { "redeploy":
      command => ":reload",
      onlyif => '(result != OK) of /deployment=matcher.war:read-attribute(name=status)',
    }`

sadly i cant get it work with "deploy" command instead of "reload".

**Comment by janorn** [comment] 2019-05-29 13:58
We are seeing the same issue on Wildfly 16. 
@mbosecke workaround works for us but would be nice if it could get fixed.
