### ISSUE TITLE
Puppet runs fail with "401 - Unauthorized"

### ISSUE THREAD

**Issue by hnijbacker** [biemond/biemond-wildfly#129] opened 2016-04-15 07:53 UTC
Puppet runs executed on wildfly nodes are experiencing spurious errors during deploying of datasources or secure deployments. An example of such an error is:

`Error: 
/Stage[main]/Keycloak::Deploy/Keycloak::Securedeployment[breedingtest.war]
  /Wildfly::Util::Resource[/subsystem=keycloak/secure-deployment=test.war]
  /Wildfly_resource[/subsystem=keycloak/secure-deployment=test.war]: 
Could not evaluate: 757: unexpected token at 
'<html><head><title>Error</title></head><body>401 - Unauthorized</body></html>'`

Observations:
- Only Wildfly 10 servers suffer from this problem. Wildfly 9 servers have no issues
- A restart of the wildfly service will temporarily solve the problem. 
- All deployments can experience errors:
  - jdbc drivers
  - datasources
  - secure deployments
- More deployments configured will increase the chance of failures
- It fails on different deployment(s) after the next Puppet run

Using tcpdump we could see that in a normal situation the flow is:

```
Request:       GET /management HTTP/1.1
Response:      HTTP/1/1 401 Unauthorized    (This is expected, the code finds the authentication protocol used (basic or digest))

Request:       POST /management (It uses a POST to perform a read-resource operation (/subsystem=keycloak/secure-deployment=<name>:read-resource(recursive=false)
Content:           application/json

Response       HTTP/1.1 200 OK

```

During failure the flow is different:

```
Request:        GET /management HTTP/1.1
Response:       HTTP/1/1 401 Unauthorized

Response:       HTTP/1/1 401 Unauthorized  => this is were Puppet fails

Request:        POST /management
Response:       HTTP/1.1 200 OK
```

Adding the following change to wildfly_cli.rb will work around the issue:

```
--- lib/puppet_x/util/wildfly_cli.rb    (revision 88f13ce70dc81775e254396c7f9a9cc92c44fa9d)
+++ lib/puppet_x/util/wildfly_cli.rb    (revision 65a85b4c82883e93173ccf695f525d36dbccb6c0)
@@ -242,6 +242,10 @@
         digest_auth = Net::HTTP::DigestAuth.new
         authz_request = Net::HTTP::Get.new @uri.request_uri
         response = @http_client.request authz_request
+
+        # Work-around for unauthorized error
+        sleep(0.1)
+
         if response['www-authenticate'] =~ /digest/i
           digest_auth.auth_header @uri, response['www-authenticate'], 'POST'
         else

```

**Comment by jairojunior** [comment] 2016-05-04 03:35
Thank you for filling up this issue. 

I have just confirmed this using Vagrant. It's only happening when the environment is provisioned for the first time... I'll try to investigate using tcpdump

**Comment by icetrain** [comment] 2016-05-13 12:53
We are seeing the same HTTP 401 errors for random WildFly resources on all our WildFly 10 server.
For now we just ignore them since the error is not consistent and sometimes 15-20 puppet runs go through with any problems and then the next one fails and then it works again and so on.

**Comment by jairojunior** [comment] 2016-10-30 15:52
I'll close this issue, but will build an acceptance test for this scenario.

**Closed by jairojunior** 2016-10-30 15:52 UTC
Labels: bug
